<template>
    <div class="text-xs-justify">
        <app-header></app-header>
        <app-nav></app-nav>
        <v-container>
             <p class="title">
            1. Acceptance of the Terms of Use
            </p>
            <span class="body-2 font-weight-medium"> The following terms and conditions, together with any referenced documents (collectively, "Terms of Use") form a legal agreement between you and your employer, employees, agents, contractors and any other entity on whose behalf you accept these terms (collectively, “you” and “your”), and ServiceNow, Inc. (“ServiceNow,” “we,” “us” and “our”). The Terms of Use apply to the demonstration services available on the website where these Terms of Use are presented, including any ServiceNow Intellectual Property (as defined below) therein (the “Demo Website”).
            By accessing or using the Demo Website, or by clicking to accept or agree to the Terms of Use when this option is made available to you, you represent that you have read and understood, and agree to be bound by these Terms of Use. If you do not agree to these Terms of Use, you may not use the Demo Website.
            The Demo Website is a collection of shared instances that automatically reset on a timed schedule. Anything input by a user of the Demo Website that remains on an instance following your use will be visible and usable to all other users that access the same instance before it is reset.  In addition to the rights provided to ServiceNow above, you hereby grant to all users of the Demo Website a royalty‑free, fully‑paid, non‑exclusive, non‑transferable, sub‑licensable, worldwide right to use any data and intellectual property provided by you to each other user of the Demo Website solely to use the Demo Website as described herein.
            </span>
            <p class="title mt-2">
            2. Prohibited Uses
            </p>
            <span class="body-2 font-weight-medium">You agree not to access or use (and shall not permit others to access or use) the Demo Website or ServiceNow Intellectual Property in any manner:

            Other than for product evaluation purposes (specifically excluding product demonstration, development, or any production or commercial purposes).
            To process, use, transmit or introduce any confidential or sensitive information of any kind, including personally identifiable information, sensitive personal data, health information of any kind, or factual data regarding your employees or third data, and particularly excluding: (1) information protected under the privacy or security regulations issued pursuant to the Health Insurance Portability and Accountability Act of 1996 (HIPAA) or subject to the Health Information Technology for Economic and Clinical Health (HITECH) Act; or (2) non‑public sensitive or personally identifiable information including but not limited to drivers license numbers, passport numbers, social security numbers, tax identification numbers, voter registration numbers or similar identifying numbers, health information, or financial information including bank, checking, credit card, debit card, or other account numbers.
            To license, sub‑license, sell, re‑sell, rent, lease, transfer, distribute or time share or otherwise make them available for access by third parties.
            To disassemble, reverse engineer, decompile or modify them or otherwise create derivative works of them.
            To access them for the purpose of developing a product or service that competes with a ServiceNow Product.
            To use them to create, use, send, store or run viruses or other harmful computer code, files, scripts, agents or other programs or engage in any other malicious act.
            To disrupt their security, integrity or operation.
            To remove or modify a copyright or other proprietary rights notice in them.
           </span>
            <p class="title mt-2">
            3. Intellectual Property
            </p>
            <span class="body-2 font-weight-medium">As between you and ServiceNow, all rights, title and interest in and to all the intellectual property rights in the ServiceNow Intellectual Property are owned exclusively by ServiceNow and its licensors, notwithstanding any other provision in these Terms of Use or any other agreement. The ServiceNow Intellectual Property is protected by United States and international laws regarding copyrights, trademarks, trade secrets and other intellectual property or proprietary rights. As used herein, “ServiceNow Intellectual Property” means the information, text, displays, images, video, audio, and user interfaces included in or generated by the Demo Website, and the design, selection and arrangement thereof, as well as the technology that is used by ServiceNow to deliver the Demo Website, including: (a) software code (whether in source or object form) including platforms and applications, hardware, algorithms, templates, graphical user interfaces, architectures, class libraries, application programming interfaces, objects, methodologies, and documentation (both printed and electronic) in existence as of the Effective Date or otherwise acquired or developed by ServiceNow apart from the services rendered under these Terms of Use; and (b) any derivative works, improvements, enhancements or extensions of the foregoing made by ether you or ServiceNow. Except as expressly provided in this Agreement, ServiceNow does not grant you (and expressly reserves) any rights, express or implied, or ownership in the ServiceNow Intellectual Property. No right, title or interest in or to the Demo Website is transferred to you. ServiceNow reserves all rights not expressly granted to you herein. You hereby grant to ServiceNow a royalty‑free, fully‑paid, non‑exclusive, non‑transferable, sub‑licensable, worldwide right to use: (a) electronic data uploaded or processed by you to the Demo Website; and (b) any software, methodologies, templates, business processes, documentation or other material authored, invented or otherwise created by you using or for use with the ServiceNow Intellectual Property provided by you to ServiceNow solely to provide the Demo Website.  Customer Technology does not include, and Customer will have no ownership of intellectual property in, ServiceNow Core Technology. Any use of the Demo Website not expressly permitted by these Terms of Use is a breach of these Terms of Use and may violate copyright, trademark and other laws. You are permitted to use the Demo Website only for legitimate business purposes related to your role as a current or prospective customer, supplier or partner of ServiceNow. You shall not copy, modify, create derivative works of, publicly display or perform, republish, download or store, or transmit any ServiceNow Intellectual Property without ServiceNow’s express prior written consent or except as expressly provided in these Terms of Use.
            ServiceNow Trademarks
            </span>
            <p class="title mt-2">
            4. Monitoring, Enforcement and Feedback
            </p>
            <span class="body-2 font-weight-medium">The Demo Website is a shared environment. ServiceNow has the right but not the obligation to:

            Terminate your access to all or part of the Demo Website for any reason or no reason, in our sole discretion, including without limitation any violation of these Terms of Use or the Privacy Policy.
            Disclose your identity to any third party who claims that material posted by you violates their rights, including their intellectual property rights or their right to privacy.
            Take appropriate legal action, including without limitation, referral to law enforcement, for any illegal or unauthorized use of the Demo Website.
            Without limiting the foregoing, ServiceNow has the right to fully cooperate with any law enforcement authorities or court order requesting or directing us to disclose the identity of anyone including any materials on or through the Demo Website. YOU WAIVE AND HOLD SERVICENOW HARMLESS FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY SERVICENOW DURING OR AS A RESULT OF ITS INVESTIGATIONS AND FROM ANY ACTIONS TAKEN AS A CONSEQUENCE OF INVESTIGATIONS BY EITHER SERVICENOW OR LAW ENFORCEMENT AUTHORITIES.

           </span>
            <p class="title mt-2">
            5. Legal Considerations
            </p>
            <span class="body-2 font-weight-medium">Regional Legal Considerations

            The owner of the Demo Website is based in the state of California in the United States. The Demo Website can be accessed from countries around the world.  Access to the Demo Website may not be legal by certain persons or in certain countries. If you access the Demo Website from outside the United States, you do so on your own initiative and are responsible for compliance with local laws. Access to the Demo Website from territories where the Demo Website or any of its services or products are illegal is prohibited. You acknowledge that you remain responsible at all times for your compliance with U.S. and all applicable export and related statutes and regulations.

            Disclaimer of Warranties

           Limitation of Liability

            EXCEPT TO THE EXTENT THAT A DISCLAIMER OF LIABILITY IS PROHIBITED UNDER APPLICABLE LAW, IN NO EVENT WILL SERVICENOW, ITS AFFILIATES AND ITS LICENSORS, SERVICE PROVIDERS, EMPLOYEES, AGENTS, OFFICERS AND DIRECTORS BE LIABLE FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, THE DEMO WEBSITE, INCLUDING ANY WEBSITE CONTENT, INCLUDING ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING, EMOTIONAL DISTRESS, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT OR OTHERWISE, EVEN IF FORESEEABLE.

            Indemnification

            You agree to defend, indemnify and hold ServiceNow, its affiliates and licensors and their respective officers, directors, employees, contractors, agents, licensors and suppliers harmless from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses or fees (including reasonable attorneys' fees and other costs of defense) resulting from your violation of these Terms of Use or your use of the Demo Website, including, without limitation, any use of the Demo Website's content, services and products other than as expressly authorized in these Terms of Use or your use of any information obtained from the Demo Website.

            Governing Law and Jurisdiction

            The Terms of Use and our Privacy Policy constitute the sole and entire agreement between you and ServiceNow with respect to the Demo Website and supersede all prior and contemporaneous understandings, agreements, representations and warranties, both written and oral, with respect to the Demo Website. For the avoidance of doubt, these Terms of Use do not supersede any Master Ordering Agreement, subscription agreement or other agreement pursuant to which you have been granted the right to use or access a ServiceNow product or service.

            © ServiceNow, Inc.  All rights reserved.
            </span>
        </v-container>
    </div>
</template>
